#! /bin/bash

if [ src/cdlScanner.ll -nt src/cdlScanner.cc ] 
then
	echo "Creating cdlScanner.cc..."
	flex -o src/cdlScanner.cc src/cdlScanner.ll
fi

if [ src/cdlParser.yy -nt src/cdlParser.cc ] 
then
	echo "Creating cdlParser.cc..."
	bison -d -v -Werror -Wall -Wno-yacc --report=all -o src/cdlParser.cc src/cdlParser.yy
fi
