#! /bin/bash

if [ cdlScanner.ll -nt cdlScanner.cc ] 
then
	echo "Creating cdlScanner.cc..."
	flex -o cdlScanner.cc cdlScanner.ll
fi

if [ cdlParser.yy -nt cdlParser.cc ] 
then
	echo "Creating cdlParser.cc..."
	bison -d -v -Werror -Wall -Wno-yacc --report=all -o cdlParser.cc cdlParser.yy
fi
