#! /bin/bash

# tested with
# flex 2.5.39
# bison (GNU Bison) 3.0.4

if [ cdlScanner.ll -nt cdlScanner.cc ] 
then
	echo "Creating cdlScanner.cc..."
	flex -o cdlScanner.cc cdlScanner.ll
fi

if [ cdlParser.yy -nt cdlParser.cc ] 
then
	echo "Creating cdlParser.cc..."
	bison -d -v -Werror -Wall -Wno-yacc --report=all -o cdlParser.cc cdlParser.yy
fi
